### ISSUE TITLE
partials et fonctions

### ISSUE THREAD

**Issue by cefomk** [Allan76370/FOAD_DWWM_09022023_Allan76370_github#1]
La découpe de ton index.php peut mieux etre organisé , dans header.php tu devrais mettre toute l'entete de ton html suivie du `<header>`.

La fonction `dd` est tres bien par contre pour la date il faut en faire une fonction que tu appelera dans ton footer.

**Comment by Allan76370** [comment]
Ok très bien, la modification est faite, tout le head ainsi que le header
est dans le fichier header.php.
Pour la date, j'ai réalisé une fonction rapide, et rappelé dans mon
index.php, ainsi qu'un <br> pour séparer ma date et ma fonction dd.

**Comment by Allan76370** [comment]
Ok super, c'est fait. Merci de ton retour Mehdi.
